"""nostrhost-protocol: cross-language NostrHost control-plane event protocol.

Public API (Python binding):

- Kind constants (``KindOperationRequest``, ``KIND_SYSTEM_EVENT``, ...).
- :class:`Verdict` and :class:`FoldResult`.
- :func:`validate_event`, :func:`fold_events` and schema/manifest loading.
"""

from __future__ import annotations

from .conformance import conformance, load_folds, load_verdicts, run_folds, run_verdicts
from .fold import FoldResult, fold, fold_events
from .kinds import (
    ADDRESSABLE_KINDS,
    CHAIN_KINDS,
    CLASS_EPHEMERAL,
    CLASS_IMMUTABLE,
    CLASS_PRURABLE,
    CLASS_REPLACEABLE,
    HEX64_D_KINDS,
    JSON_CONTENT_KINDS,
    Kind,
    NOTICE_KINDS,
    SIGNER_TYPES,
    all_kinds,
    chain_kinds,
    is_custom_kind,
    retention_class,
)
from .kinds import (  # noqa: E402 — module-level int aliases (KindOperationRequest, ...)
    AppData,
    AuthChallenge,
    BackupEvent,
    BlockedRelays,
    BuildAttestation,
    Capability,
    Delegation,
    DelegationRevocation,
    ExecutionProgress,
    ExecutionResult,
    ExecutionStarted,
    IdentityDefinition,
    MuteList,
    Nip98,
    OperationApproval,
    OperationRejection,
    OperationRequest,
    OwnerApproval,
    PermissionSet,
    RelayList,
    RepositoryAnnouncement,
    SecurityEvent,
    ServiceEvent,
    StateBundle,
    SystemEvent,
    TrustPolicy,
)
from .kinds import (  # noqa: E402 — Go-style aliases
    KindAppData,
    KindAuthChallenge,
    KindBackupEvent,
    KindBlockedRelays,
    KindBuildAttestation,
    KindCapability,
    KindDelegation,
    KindDelegationRevocation,
    KindExecutionProgress,
    KindExecutionResult,
    KindExecutionStarted,
    KindIdentityDefinition,
    KindMuteList,
    KindNip98,
    KindOperationApproval,
    KindOperationRejection,
    KindOperationRequest,
    KindOwnerApproval,
    KindPermissionSet,
    KindRelayList,
    KindRepositoryAnnouncement,
    KindSecurityEvent,
    KindServiceEvent,
    KindStateBundle,
    KindSystemEvent,
    KindTrustPolicy,
)
from .kinds import (  # noqa: E402 — legacy aliases
    KIND_APP_DATA,
    KIND_AUTH_CHALLENGE,
    KIND_BACKUP_EVENT,
    KIND_BLOCKED_RELAYS,
    KIND_BUILD_ATTESTATION,
    KIND_CAPABILITY,
    KIND_DELEGATION,
    KIND_DELEGATION_REVOCATION,
    KIND_EXECUTION_PROGRESS,
    KIND_EXECUTION_RESULT,
    KIND_EXECUTION_STARTED,
    KIND_IDENTITY_DEFINITION,
    KIND_MUTE_LIST,
    KIND_NIP98,
    KIND_OPERATION_APPROVAL,
    KIND_OPERATION_REJECTION,
    KIND_OPERATION_REQUEST,
    KIND_OWNER_APPROVAL,
    KIND_PERMISSION_SET,
    KIND_RELAY_LIST,
    KIND_REPOSITORY_ANNOUNCEMENT,
    KIND_SECURITY_EVENT,
    KIND_SERVICE_EVENT,
    KIND_STATE_BUNDLE,
    KIND_SYSTEM_EVENT,
    KIND_TRUST_POLICY,
)
from .manifest import (
    KindSpec,
    duplicate_kinds,
    find_kind,
    iter_kinds,
    load_manifest,
    manifest_path,
    rejection_codes_for,
    schema_reference_for,
    validate_manifest,
)
from .schemas import (
    fixtures_dir,
    load_all_schemas,
    load_schema,
    schema_path_for,
    schemas_dir,
    spec_root,
)
from .validate import declares_revision, is_hex64, revision_of, validate, validate_event
from .verdict import Verdict

__version__ = "0.1.0"

__all__ = [
    "Verdict",
    "FoldResult",
    "validate_event",
    "validate",
    "fold",
    "fold_events",
    "revision_of",
    "declares_revision",
    "is_hex64",
    "Kind",
    "KindSpec",
    "conformance",
    "load_verdicts",
    "load_folds",
    "run_verdicts",
    "run_folds",
    "load_manifest",
    "manifest_path",
    "iter_kinds",
    "find_kind",
    "duplicate_kinds",
    "validate_manifest",
    "rejection_codes_for",
    "schema_reference_for",
    "load_schema",
    "load_all_schemas",
    "schema_path_for",
    "spec_root",
    "schemas_dir",
    "fixtures_dir",
    "retention_class",
    "is_custom_kind",
    "chain_kinds",
    "all_kinds",
    "JSON_CONTENT_KINDS",
    "ADDRESSABLE_KINDS",
    "HEX64_D_KINDS",
    "SIGNER_TYPES",
    "CHAIN_KINDS",
    "NOTICE_KINDS",
    "CLASS_IMMUTABLE",
    "CLASS_REPLACEABLE",
    "CLASS_PRURABLE",
    "CLASS_EPHEMERAL",
]